In [2]:
import pandas as pd

df = pd.read_csv('../Original Data/billboard.csv', encoding = 'latin')
df

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,2000,Ghostface Killah,Cherchez LaGhost,3:04,R&B,2000-08-05,2000-08-05,98,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,2000,"Smith, Will",Freakin' It,3:58,Rap,2000-02-12,2000-02-12,99,99.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,2000,Zombie Nation,Kernkraft 400,3:30,Rock,2000-09-02,2000-09-02,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,2000,"Eastsidaz, The",Got Beef,3:58,Rap,2000-07-01,2000-07-01,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,2000,Fragma,Toca's Miracle,3:22,R&B,2000-10-28,2000-10-28,99,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
to_be_melted = list(df.columns[7:])
melted = df.melt(id_vars = ['artist.inverted', 'track', 'date.entered'], var_name = 'week', value_vars = to_be_melted, value_name = 'place')
music_detail = df.drop(columns=list(df.columns[5:]))
music_detail.sort_values(['artist.inverted'], inplace=True)
music_detail.reset_index(drop=True, inplace=True)

In [4]:
melted.dropna(axis=0, inplace=True)

In [5]:
melted.sort_values(['artist.inverted', 'date.entered', 'week'], inplace=True)
melted.reset_index(drop=True, inplace=True)
better_time = list(pd.to_datetime(melted['date.entered']))
melted['date.entered'] = better_time
melted['week'] = melted['week'].str.lstrip('x')
melted['week'] = melted['week'].str.rstrip('.week')
melted['week'] = melted['week'].str.rstrip('st|nd|rd|th')

,artist.inverted,track,date.entered,week,place
0,2 Pac,Baby Don't Cry (Keep Ya Head Up II),2000-02-26,1,87.0
1,2 Pac,Baby Don't Cry (Keep Ya Head Up II),2000-02-26,2,82.0
2,2 Pac,Baby Don't Cry (Keep Ya Head Up II),2000-02-26,3,72.0
3,2 Pac,Baby Don't Cry (Keep Ya Head Up II),2000-02-26,4,77.0
4,2 Pac,Baby Don't Cry (Keep Ya Head Up II),2000-02-26,5,87.0
...,...,...,...,...,...
5302,matchbox twenty,Bent,2000-04-29,5,22.0
5303,matchbox twenty,Bent,2000-04-29,6,21.0
5304,matchbox twenty,Bent,2000-04-29,7,18.0
5305,matchbox twenty,Bent,2000-04-29,8,16.0
5306,matchbox twenty,Bent,2000-04-29,9,13.0

In [57]:
for i in range(len(melted)):
    melted.loc[i, 'date.entered'] = melted.loc[i, 'date.entered'] + pd.DateOffset(days = 7*(int(melted.loc[i, 'week']) - 1))
    melted.loc[i, 'week'] = melted.loc[i, 'date.entered'] + pd.DateOffset(days = 7)
melted

,artist.inverted,track,date.entered,week,place
0,2 Pac,Baby Don't Cry (Keep Ya Head Up II),2000-02-26,2000-03-04 00:00:00,87.0
1,2 Pac,Baby Don't Cry (Keep Ya Head Up II),2000-03-04,2000-03-11 00:00:00,82.0
2,2 Pac,Baby Don't Cry (Keep Ya Head Up II),2000-03-11,2000-03-18 00:00:00,72.0
3,2 Pac,Baby Don't Cry (Keep Ya Head Up II),2000-03-18,2000-03-25 00:00:00,77.0
4,2 Pac,Baby Don't Cry (Keep Ya Head Up II),2000-03-25,2000-04-01 00:00:00,87.0
...,...,...,...,...,...
5302,matchbox twenty,Bent,2000-05-27,2000-06-03 00:00:00,22.0
5303,matchbox twenty,Bent,2000-06-03,2000-06-10 00:00:00,21.0
5304,matchbox twenty,Bent,2000-06-10,2000-06-17 00:00:00,18.0
5305,matchbox twenty,Bent,2000-06-17,2000-06-24 00:00:00,16.0
5306,matchbox twenty,Bent,2000-06-24,2000-07-01 00:00:00,13.0

In [58]:
melted['week'] = melted['week'].astype('datetime64[ns]')
melted = melted.rename(columns={'artist.inverted' : 'artist', 'date.entered' : 'week start', 'week' : 'week end'})

In [64]:

melted.to_csv(r'..\Analysis Data\music_top_list.csv')

In [65]:

music_detail.to_csv(r'..\Analysis Data\music_details.csv')

In [66]:
melted.head(10)

,artist,track,week start,week end,place
0,2 Pac,Baby Don't Cry (Keep Ya Head Up II),2000-02-26,2000-03-04,87.0
1,2 Pac,Baby Don't Cry (Keep Ya Head Up II),2000-03-04,2000-03-11,82.0
2,2 Pac,Baby Don't Cry (Keep Ya Head Up II),2000-03-11,2000-03-18,72.0
3,2 Pac,Baby Don't Cry (Keep Ya Head Up II),2000-03-18,2000-03-25,77.0
4,2 Pac,Baby Don't Cry (Keep Ya Head Up II),2000-03-25,2000-04-01,87.0
5,2 Pac,Baby Don't Cry (Keep Ya Head Up II),2000-04-01,2000-04-08,94.0
6,2 Pac,Baby Don't Cry (Keep Ya Head Up II),2000-04-08,2000-04-15,99.0
7,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,2000-09-02,2000-09-09,91.0
8,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,2000-09-09,2000-09-16,87.0
9,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,2000-09-16,2000-09-23,92.0

In [67]:
music_detail.head(10)

,year,artist.inverted,track,time,genre
0,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap
1,2000,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B
2,2000,3 Doors Down,Kryptonite,3:53,Rock
3,2000,3 Doors Down,Loser,4:24,Rock
4,2000,504 Boyz,Wobble Wobble,3:35,Rap
5,2000,98Â¡,Give Me Just One Night (Una Noche),3:24,Rock
6,2000,A*Teens,Dancing Queen,3:44,Pop
7,2000,Aaliyah,Try Again,4:03,Rock
8,2000,Aaliyah,I Don't Wanna,4:15,Rock
9,2000,"Adams, Yolanda",Open My Heart,5:30,Gospel